In [55]:
import numpy as np
a = np.array([10,20,30,40,50])
print("1d array: ",a ,type(a))
#print(a.dtype)

a = np.array([[10,20],[30,40],[50,45]], dtype='S')
print("2d array: \n",a ,type(a))

a = np.zeros([3,5])
print(a)
b = np.zeros(5)
print(b)
a = np.ones([3,6])
print(a)
b = np.ones(6)
print(b)

a = np.zeros([3,5,4])
print(a)

#fotron order arr
a= np.ones([6,3], order='F')
print(a)

arr = np.arange(10)
print("arr using arange: ",arr)


1d array:  [10 20 30 40 50] <class 'numpy.ndarray'>
2d array: 
 [[b'10' b'20']
 [b'30' b'40']
 [b'50' b'45']] <class 'numpy.ndarray'>
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[0. 0. 0. 0. 0.]
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
[1. 1. 1. 1. 1. 1.]
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
arr using arange:  [0 1 2 3 4 5 6 7 8 9]


In [56]:
import numpy as np
arr1 = np.linspace(0,5,num=10)
print("using linspace: ",arr1)

arr1 = np.linspace(0,5,num=10, endpoint=False)
print("using linspace: ",arr1)

arr1 = np.linspace(0,5,num=10,retstep=True)
print("using linspace: ",arr1)

#empty arr
a = np.empty([2,3]) #fill last data of memory
print("empty array: \n",a)

a = np.full((2,3),5) #fill last data of memory
print("full array: \n",a)

using linspace:  [0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]
using linspace:  [0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
using linspace:  (array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ]), np.float64(0.5555555555555556))
empty array: 
 [[1. 1. 1.]
 [1. 1. 1.]]
full array: 
 [[5 5 5]
 [5 5 5]]


In [57]:
import numpy as np

#   accessing the array

a= np.array([[1,2,3,4,5],[6,7,8,99,10]])
print(a[1,3])

a= np.array([
    [[1,2,3,4,5],[6,7,8,99,10]],
            [[111,12,13,14,15],[16,17,18,199,110]]
            ])
print(a[1,1,3])
print(a[1,1,-1])

#   Slicing    [start,stop,step]
s = np.array([1,22,65,78,11,12,13,14,15])
print(s[1:4:])
print(s[1:9:2])

s = np.array([[1,2,3,4,5],[6,7,8,99,10]])
print("slicing 2d arr:\n",s[0:2,1:3])

a= np.array([
    [[1,2,3,4,5],[6,7,8,99,10]],
            [[111,12,13,14,15],[16,17,18,199,110]]
            ])
print("slicing in 3d arr\n", a[0,1,2])

print(a.reshape(-1))

99
199
110
[22 65 78]
[22 78 12 14]
slicing 2d arr:
 [[2 3]
 [7 8]]
slicing in 3d arr
 8
[  1   2   3   4   5   6   7   8  99  10 111  12  13  14  15  16  17  18
 199 110]


In [75]:
print("copy wala part:")
s = np.array([1,22,65,78,11,12,13,14,15])
x = s.copy()
s[0]=56
print(s)
print(x)

print("view wala part:")
y = np.array([1,22,65,78,11,12,13,14,15])
z = s.view()
y[0]=56
print(y)
print(z)

y = np.array([1,22,65,78,11,12,13,14,15], ndmin=5)
print(y)

s = np.array([[1,2,3,6,5],[6,7,8,99,10]])
print(s.ravel())
print(np.unique(s))

print(s.max(),s.min())

print("sum: ",s.sum())
print("std deviation: ",s.std(),"and", np.std(s))
print("square root: ",np.sqrt(s))

s = s.reshape(5,2)
q = np.array([[111,12,13,14,15],[16,17,18,199,110]])
res = s.dot(q)
print(res)



copy wala part:
[56 22 65 78 11 12 13 14 15]
[ 1 22 65 78 11 12 13 14 15]
view wala part:
[56 22 65 78 11 12 13 14 15]
[56 22 65 78 11 12 13 14 15]
[[[[[ 1 22 65 78 11 12 13 14 15]]]]]
[ 1  2  3  6  5  6  7  8 99 10]
[ 1  2  3  5  6  7  8 10 99]
99 1
sum:  147
std deviation:  28.2207370562854 and 28.2207370562854
square root:  [[1.         1.41421356 1.73205081 2.44948974 2.23606798]
 [2.44948974 2.64575131 2.82842712 9.94987437 3.16227766]]
[[  143    46    49   412   235]
 [  429   138   147  1236   705]
 [  651   162   173  1264   735]
 [  905   220   235  1690   985]
 [11149  1358  1467  3376  2585]]


In [59]:
import numpy as np

a= np.random.rand(2,3,4)
print(a)

[[[0.00711101 0.89351351 0.1851032  0.989093  ]
  [0.01492486 0.79869941 0.68697992 0.31040151]
  [0.72144777 0.00598632 0.52423045 0.07572791]]

 [[0.11461143 0.52778869 0.45322095 0.78798297]
  [0.78734101 0.65369575 0.72018842 0.57858502]
  [0.9228932  0.78969279 0.22788503 0.96206366]]]
