In [9]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([[4, 5, 6],
              [7, 8, 9]])
a2 = a.reshape(1, 3)
res = np.concatenate((a2, b),axis=0)
print("/combined array:\n", res)

/combined array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [19]:
arr = np.array([[1,2,3],
                [4,5,6]])
flat = arr.flatten()
print(flat)
flat2 = arr.ravel()
print(flat2)
flat3= arr.reshape(-1)
print(flat3)

a= np.array([11,22,33,44,55,66])
print("orignal array: ",a)
b= a[::-1]
print("reverse array: ",b)

[1 2 3 4 5 6]
[1 2 3 4 5 6]
[1 2 3 4 5 6]
orignal array:  [11 22 33 44 55 66]
reverse array:  [66 55 44 33 22 11]


In [20]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
print("Array:\n", arr)

print("Max value:", arr.max())
print("Min value:", arr.min())

rows, cols = arr.shape
print("Rows:", rows, "Columns:", cols)

#Each element
print("All elements:")
for i in range(rows):
    for j in range(cols):
        print(arr[i][j], end=" ")
    print()

print("Specific element:", arr[1][2])

total = 0
for i in range(rows):
    for j in range(cols):
        total += arr[i][j]
print("Sum using loop:", total)
print("Sum using numpy:", arr.sum())


a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print("Add: ", a + b)
print("Sub: ", a - b)
print("Multi: ", a * b)
print("Divi: ", a / b)

Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Max value: 9
Min value: 1
Rows: 3 Columns: 3
All elements:
1 2 3 
4 5 6 
7 8 9 
Specific element: 6
Sum using loop: 45
Sum using numpy: 45
Add:  [5 7 9]
Sub:  [-3 -3 -3]
Multi:  [ 4 10 18]
Divi:  [0.25 0.4  0.5 ]


In [ ]:
# Iterate 3D array using for loop and nditer

In [26]:
import numpy as np

arr1 = np.array([[3, 4, 5],
                 [6, 7, 8]])
arr2 = np.array([[1, 0, 2],
                 [3, 4, 5]])
avg = (arr1 + arr2) / 2
print("Average:\n", avg)

comb = np.concatenate((arr1, arr2))

print("Mean:", np.mean(comb))
print("Median:", np.median(comb))


#mode is not in np
flat = arr.flatten()
values, counts = np.unique(flat, return_counts=True) #values me values aayegi or count me how many times it appears aaga
mode = values[np.argmax(counts)]
print("Mode:", mode)

Average:
 [[2.  2.  3.5]
 [4.5 5.5 6.5]]
Mean: 4.0
Median: 4.0
Mode: 1
