In [9]:
import numpy as np
arr = np.array([[6, -8, 73, -110], [np.nan, -8, 0, 94]])
arr_no_nan = np.nan_to_num(arr, nan=0)
# Interchange rows and columns (Transpose)
result = arr_no_nan.T

print("After replacing NaN with 0:\n", arr_no_nan)
print("After transpose:\n", result)

After replacing NaN with 0:
 [[   6.   -8.   73. -110.]
 [   0.   -8.    0.   94.]]
After transpose:
 [[   6.    0.]
 [  -8.   -8.]
 [  73.    0.]
 [-110.   94.]]


In [10]:
import numpy as np
arr3d = np.random.randint(1,10,(2,3,4))
# Move axis (0 → 2)
moved = np.moveaxis(arr3d, 0, 2)    #np.moveaxis(arr3d,0,-1) bhi likh sakte he bcz hum 0 element ko last me le jaa rahe he
print("array3d: \n",arr3d)
print("Original shape:", arr3d.shape)
print("New shape:", moved.shape)

array3d: 
 [[[6 7 2 4]
  [1 3 8 9]
  [6 7 2 3]]

 [[6 8 1 3]
  [1 2 7 9]
  [8 4 4 2]]]
Original shape: (2, 3, 4)
New shape: (3, 4, 2)


In [ ]:
import numpy as np
arr = np.array([[1, np.nan, 3],
                [4, 5, np.nan],
                [7, 8, 9]])
col_mean = np.nanmean(arr, axis=0)
# Replace nan with column mean
inds = np.where(np.isnan(arr))
print(inds)
arr[inds] = np.take(col_mean, inds[1])
print(arr)

arr = np.array([2, -3, 5, -1, 0])
arr[arr < 0] = 0
print(arr)

(array([0, 1]), array([1, 2]))
[[1.  6.5 3. ]
 [4.  5.  6. ]
 [7.  8.  9. ]]
[2 0 5 0 0]
