In [7]:
import numpy as np


#Convert 1D array to 2D & Print Attributes
arr1d = np.array([1, 2, 3, 4, 5, 6])
arr2d = arr1d.reshape(2, 3)

print("2D Array:\n", arr2d)
print("Shape:", arr2d.shape)
print("Dimensions:", arr2d.ndim)
print("Data Type:", arr2d.dtype)
print("Item Size (in bytes):", arr2d.itemsize)

#create a 3x3 NumPy array of all 9
arr_all_9 = np.full((3, 3), 9)
print(arr_all_9)

# 1D array of 10 barabar spaced values bet 25 and 125
spaced_arr = np.linspace(25, 125, 10)
print(spaced_arr)

#convert a list into a NumPy array
py_list = [10, 20, 30, 40]
list_to_arr = np.array(py_list)
print("NumPy Array:", list_to_arr)

2D Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Dimensions: 2
Data Type: int64
Item Size (in bytes): 8
[[9 9 9]
 [9 9 9]
 [9 9 9]]
[ 25.          36.11111111  47.22222222  58.33333333  69.44444444
  80.55555556  91.66666667 102.77777778 113.88888889 125.        ]
NumPy Array: [10 20 30 40]


In [8]:
import numpy as np

#Reverse a 1D NumPy array
arr = np.array([1, 2, 3, 4, 5])
revarr = arr[::-1]
print("Original:", arr)
print("Reversed:", revarr)

#create a 4x4x3 array and extract value at 2nd set, 1st row, last column
arr_3d = np.arange(1, 49).reshape(4, 4, 3) 
extractedval = arr_3d[1, 0, -1]
print("Extracted Value:", extractedval)

#create a 4x4 and Extract Odd Rows and Even Columns
matrix = np.arange(1, 17).reshape(4, 4)
print("Original 4x4 Matrix:\n", matrix)

odd_rows_even_cols = matrix[1::2, 0::2]
print("Extracted Result:\n", odd_rows_even_cols)

#slice first two rows & columns of 2nd set from a 4x4x3 array
sliced_3d = arr_3d[1, 0:2, 0:2]
print(sliced_3d)

Original: [1 2 3 4 5]
Reversed: [5 4 3 2 1]
Extracted Value: 15
Original 4x4 Matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Extracted Result:
 [[ 5  7]
 [13 15]]
[[13 14]
 [16 17]]


In [9]:
import numpy as np

#Replace all odd numbers with -1 using a for loop
grid = np.array([[23, 56, 78, 93], [71, 82, 13, 24]])

for i in range(grid.shape[0]):
    for j in range(grid.shape[1]):
        if grid[i, j] % 2 != 0:
            grid[i, j] = -1
print(grid)

#Get indices of non-zero elements
nonzero_arr = np.array([1, 0, 2, 0, 3, 0, 4])
indices = np.nonzero(nonzero_arr)
print("Indices:", indices[0])

#element-wise Arithmetic Operations
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("Add: ", a + b)
print("Multi: ", a * b)

#dot Product of two arrays
arr1 = np.array([15, 20, 25])
arr2 = np.array([10, 40, 37])
res = np.dot(arr1, arr2)
print("Dot Product:",res)

[[-1 56 78 -1]
 [-1 82 -1 24]]
Indices: [0 2 4 6]
Add:  [5 7 9]
Multi:  [ 4 10 18]
Dot Product: 1875
